<?php

namespace Database\Seeders;

use App\Models\Categoria;
use App\Models\Estado;
use App\Models\GestionHumana;
use App\Models\Municipio;
use App\Models\Redi;
use App\Models\TipoPersonal;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class GestionHumanaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $trabajadores = [
            [
                "cedula" => "5362838",
                "nombre" => "CLAUDIO ANTONIO",
                "apellido" => "PARRA PEREZ",
                "telefono" => "0414-4693785",
                "correo" => "claudioparraperez@gmail.com",
                "labor" => "PROMOTORES",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "FRANCISCO DE MIRANDA",
                "parroquia" => "CALABOZO",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "6415182",
                "nombre" => "ALDO",
                "apellido" => "MARTINEZ MOLINA",
                "telefono" => "0424-2609346",
                "correo" => "gabrielagota91@gmail.com",
                "labor" => "OBRERO",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "JUAN GERMAN ROSCIO",
                "parroquia" => "SAN JUAN",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "8618153",
                "nombre" => "JOSE BENJAMIN",
                "apellido" => "GARRIDO",
                "telefono" => "4262403922",
                "correo" => "delvalle01bella@gmail.com",
                "labor" => "PROMOTORES",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "SAN GERONIMO DE GUAYABAL",
                "parroquia" => "CAZORLA",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "8785462",
                "nombre" => "VIRGINIA NATIVIDAD",
                "apellido" => "JIMENEZ",
                "telefono" => "0424-2337372",
                "correo" => "virginianatividad@gmail.com",
                "labor" => "PROMOTORES",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "JUAN GERMAN ROSCIO",
                "parroquia" => "SAN JUAN",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "8787965",
                "nombre" => "MALVA JOSEFINA",
                "apellido" => "GONZALEZ MAICA",
                "telefono" => "0424-2163799",
                "correo" => "malvag177@gmail.com",
                "labor" => "OBRERO",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "JUAN GERMAN ROSCIO",
                "parroquia" => "SAN JUAN",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "8998995",
                "nombre" => "RAFAEL ELOY",
                "apellido" => "LICON CADENA",
                "telefono" => "0414-4442387",
                "correo" => "rafaellicon8998995@gmail.com",
                "labor" => "PROMOTORES",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "CAMAGUAN",
                "parroquia" => "CAMAGUAN",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "8999294",
                "nombre" => "RAMON ANTONIO",
                "apellido" => "MORALES NIEVES",
                "telefono" => "0416-2389654",
                "correo" => "ramonmorales2101@gmail.com",
                "labor" => "PROMOTORES",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "JUAN GERMAN ROSCIO",
                "parroquia" => "SAN JUAN",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "9876709",
                "nombre" => "JOSE",
                "apellido" => "GOMEZ",
                "telefono" => "0424-3465507",
                "correo" => "2000siempre@gmail.com",
                "labor" => "PROMOTORES",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "CAMAGUAN",
                "parroquia" => "CAMAGUAN",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "9888440",
                "nombre" => "FRANCYS NATIVIDAD",
                "apellido" => "GUTIERREZ ALEJOS",
                "telefono" => "0424-3548269",
                "correo" => "guarico2023@gmail.com",
                "labor" => "PROMOTORES",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "JUAN GERMAN ROSCIO",
                "parroquia" => "SAN JUAN",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "9890794",
                "nombre" => "NANCY COROMOTO",
                "apellido" => "LAYA HERNANDEZ",
                "telefono" => "0414-9025589",
                "correo" => "coromotolaya@hotmail.com",
                "labor" => "PROMOTORES",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "JUAN GERMAN ROSCIO",
                "parroquia" => "SAN JUAN",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "9892363",
                "nombre" => "ALIDA DEL CARMEN",
                "apellido" => "ARREAZA IBARRA",
                "telefono" => "0412-7451607",
                "correo" => "alidadl.2605@gmail.com",
                "labor" => "ADMINISTRATIVO",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "JUAN GERMAN ROSCIO",
                "parroquia" => "SAN JUAN",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "10492988",
                "nombre" => "MIGUEL ANGEL",
                "apellido" => "OLIVARES",
                "telefono" => "0424-2986958",
                "correo" => "mangel1770@gmail.com",
                "labor" => "PROMOTORES",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "JUAN GERMAN ROSCIO",
                "parroquia" => "SAN JUAN",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "10672757",
                "nombre" => "MARIA NEIDA",
                "apellido" => "FRANCO MARTINEZ",
                "telefono" => "0414-4754064",
                "correo" => null,
                "labor" => "ADMINISTRATIVO",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "JUAN GERMAN ROSCIO",
                "parroquia" => "SAN JUAN",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "10673823",
                "nombre" => "NOELIA CASILDA",
                "apellido" => "OCHOA VILLASMIL",
                "telefono" => "0424-3767809",
                "correo" => "nohelianei@hotmail.com",
                "labor" => "ADMINISTRATIVO",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "JUAN GERMAN ROSCIO",
                "parroquia" => "SAN JUAN",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "11134015",
                "nombre" => "DECSY DE LAS MERCEDE",
                "apellido" => "PEDROZA DE WEFFER",
                "telefono" => "0412-2142728",
                "correo" => "decsymer@gmail.com",
                "labor" => "PROMOTORES",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "JUAN GERMAN ROSCIO",
                "parroquia" => "SAN JUAN",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "11631827",
                "nombre" => "JOSE MIGUEL",
                "apellido" => "RUIZ AREVALO",
                "telefono" => "0426-3382907",
                "correo" => "ruizrevalojosemiguel@gmail.com",
                "labor" => "PROMOTORES",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "PEDRO ZARAZA",
                "parroquia" => "ZARAZA",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "11846964",
                "nombre" => "SUSILEIVY",
                "apellido" => "CARPIO",
                "telefono" => "0412-4520969",
                "correo" => "susileivy@gmail.com",
                "labor" => "PROMOTORES",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "JOSE FELIX RIBAS",
                "parroquia" => "TUCUPIDO",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "12171076",
                "nombre" => "PENELOPE DEL MAR",
                "apellido" => "CORDERO DE RIOS",
                "telefono" => "0412-4326272",
                "correo" => "penelopecordeo@gmail.com",
                "labor" => "PROMOTORES",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "EL SOCORRO",
                "parroquia" => "SOCORRO",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "12363488",
                "nombre" => "CESAR AUGUSTO",
                "apellido" => "CARRASQUEL CAMPOS",
                "telefono" => "0412-8894254",
                "correo" => "cesarcarrasquel03@gmail.com",
                "labor" => "PROMOTORES",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "JOSE FELIX RIBAS",
                "parroquia" => "SAN RAFAEL DE LAYA",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "12636157",
                "nombre" => "JOSE HERIBERTO",
                "apellido" => "SALAZAR",
                "telefono" => "0412-2126240",
                "correo" => null,
                "labor" => "OBRERO",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "JUAN GERMAN ROSCIO",
                "parroquia" => "SAN JUAN",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "12840320",
                "nombre" => "JOSE GREGORIO",
                "apellido" => "HERNANDEZ RODRIGUEZ",
                "telefono" => "0412-2379231",
                "correo" => "josehr2015@gmail.com",
                "labor" => "ADMINISTRATIVO",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "JUAN GERMAN ROSCIO",
                "parroquia" => "SAN JUAN",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "12842913",
                "nombre" => "MONICA CECILIA",
                "apellido" => "CARPIO BRAVO",
                "telefono" => "0416-1438750",
                "correo" => "monica12842@gmail.com",
                "labor" => "PROMOTORES",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "JULIAN MELLADO",
                "parroquia" => "EL SOMBRERO",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "13150897",
                "nombre" => "YOLANDA MARIA",
                "apellido" => "GRATEROL MARTINEZ",
                "telefono" => "0424-1828691",
                "correo" => "vocado180gmail.com",
                "labor" => "PROMOTORES",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "ORTIZ",
                "parroquia" => "SAN LORENZO DE TIZNADO",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "13447684",
                "nombre" => "GEORGINA ELOISA",
                "apellido" => "ALTUVE RODRIGUEZ",
                "telefono" => "0424-3706808",
                "correo" => "altuve486@gmail.com",
                "labor" => "ADMINISTRATIVO",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "JUAN GERMAN ROSCIO",
                "parroquia" => "SAN JUAN",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "13732130",
                "nombre" => "GABRIEL SALVADOR",
                "apellido" => "LARA ASCANIO",
                "telefono" => "0424-3208372",
                "correo" => "gabriellara92@gmail.com",
                "labor" => "PROMOTORES",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "JUAN GERMAN ROSCIO",
                "parroquia" => "SAN JUAN",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "13820555",
                "nombre" => "MARIELA DEL VALLE",
                "apellido" => "MORA GARRIDO",
                "telefono" => "0416-5110882",
                "correo" => "moramariela2@gmail.com",
                "labor" => "PROMOTORES",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "FRANCISCO DE MIRANDA",
                "parroquia" => "CALABOZO",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "14147382",
                "nombre" => "ELIZABETH",
                "apellido" => "ORTEGA RODRIGUEZ",
                "telefono" => "0426-5430071",
                "correo" => "eo231180@gmail.com",
                "labor" => "ADMINISTRATIVO",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "JUAN GERMAN ROSCIO",
                "parroquia" => "SAN JUAN",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "14539923",
                "nombre" => "YORIS DEL VALLE",
                "apellido" => "TOVAR",
                "telefono" => "0412-4064666",
                "correo" => "yoristovar8@gmail.com",
                "labor" => "PROMOTORES",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "FRANCISCO DE MIRANDA",
                "parroquia" => "CALABOZO",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "14643043",
                "nombre" => "MARYURIS LISBETH",
                "apellido" => "GUILLEN TORRES",
                "telefono" => "0412-2700414",
                "correo" => "ligia61torres@gmail.com",
                "labor" => "ADMINISTRATIVO",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "JUAN GERMAN ROSCIO",
                "parroquia" => "SAN JUAN",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "14871183",
                "nombre" => "LUIS ENRIQUE",
                "apellido" => "GILMOND PADILLA",
                "telefono" => "0412-1345231",
                "correo" => "luisgilmond@hotmail.com",
                "labor" => "PROMOTORES",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "JUAN GERMAN ROSCIO",
                "parroquia" => "SAN JUAN",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "14871707",
                "nombre" => "JOHSER ARNALDO",
                "apellido" => "SARMIENTO TORO",
                "telefono" => "0424-3307566",
                "correo" => "johsersarmiento@gmail.com",
                "labor" => "ADMINISTRATIVO",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "JUAN GERMAN ROSCIO",
                "parroquia" => "SAN JUAN",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "14926319",
                "nombre" => "YUSLAY DEL CARMEN",
                "apellido" => "GAONA MARIN",
                "telefono" => "0412-4822111",
                "correo" => "gaonayuslay@gmail.com",
                "labor" => "PROMOTORES",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "JOSE TADEO MONAGAS",
                "parroquia" => "ALTAGRACIA DE ORITUCO",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "15081760",
                "nombre" => "ANGEL HELIUT",
                "apellido" => "GALLARDO DELFINO",
                "telefono" => "0412-5724720",
                "correo" => "heliutd@gmail.com",
                "labor" => "OBRERO",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "JUAN GERMAN ROSCIO",
                "parroquia" => "SAN JUAN",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "15480036",
                "nombre" => "JESUS ALBERTO",
                "apellido" => "SANCHEZ BALDONADO",
                "telefono" => "0414-0494500",
                "correo" => "adrianalopez686@gmail.com",
                "labor" => "PROMOTORES",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "FRANCISCO DE MIRANDA",
                "parroquia" => "CALABOZO",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "15711398",
                "nombre" => "LENON GABRIEL",
                "apellido" => "CACHUTT WEFFER",
                "telefono" => "0412-2993632",
                "correo" => "lennongabrielacachutt@gmail.com",
                "labor" => "PROMOTORES",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "ORTIZ",
                "parroquia" => "SAN JOSE",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "16075165",
                "nombre" => "RAMON LUIS",
                "apellido" => "VIVAS GABBI",
                "telefono" => "0416-6447193",
                "correo" => "rlvg12@hotmail.com",
                "labor" => "ADMINISTRATIVO",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "JUAN GERMAN ROSCIO",
                "parroquia" => "SAN JUAN",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "16192970",
                "nombre" => "MARIA CIRILA",
                "apellido" => "MARTINEZ AGUANE",
                "telefono" => "0424-3801792",
                "correo" => "marimar1201@gmail.com",
                "labor" => "PROMOTORES",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "SAN JOSE DE GUARIBE",
                "parroquia" => "SAN JOSE DE GUARIBE",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "16505385",
                "nombre" => "RUDY DEL VALLE",
                "apellido" => "RUIZ HERNANDEZ",
                "telefono" => "0416-4367529",
                "correo" => "rudyhernand@gmail.com",
                "labor" => "ADMINISTRATIVO",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "JUAN GERMAN ROSCIO",
                "parroquia" => "SAN JUAN",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "16789778",
                "nombre" => "DEIBIS ANTONIO",
                "apellido" => "PERAZA SOTILLO",
                "telefono" => "0412-9259077",
                "correo" => "deibissotillo15@gmail.com",
                "labor" => "PROMOTORES",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "PEDRO ZARAZA",
                "parroquia" => "ZARAZA",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "16790705",
                "nombre" => "MARGARITA JOSEFINA",
                "apellido" => "GONZALEZ",
                "telefono" => "0426-4307775",
                "correo" => "margareg2022@gmail.com",
                "labor" => "PROMOTORES",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "PEDRO ZARAZA",
                "parroquia" => "ZARAZA",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "16804316",
                "nombre" => "KRISBEL EDDY",
                "apellido" => "SANABRIA ROJAS",
                "telefono" => "0424-3590403",
                "correo" => "krisbelsanabria85@gmail.com",
                "labor" => "PROMOTORES",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "JUAN GERMAN ROSCIO",
                "parroquia" => "SAN JUAN",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "16975171",
                "nombre" => "MILAGROS DE LOS ANGELES",
                "apellido" => "SOTILLO MORALES",
                "telefono" => "0416-0459350",
                "correo" => "milagrosotillo727@gmail.com",
                "labor" => "ADMINISTRATIVO",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "LEONARDO INFANTE",
                "parroquia" => "VALLE DE LA PASCUA",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "16999462",
                "nombre" => "WARNER JOSE",
                "apellido" => "MARCHAN PEREZ",
                "telefono" => "0424-2951738",
                "correo" => "warnermarchan55@gmail.com",
                "labor" => "PROMOTORES",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "LEONARDO INFANTE",
                "parroquia" => "VALLE DE LA PASCUA",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "16999713",
                "nombre" => "ABELIT CAROLINA",
                "apellido" => "SEIJAS ORTEGA",
                "telefono" => "0426-3469773",
                "correo" => "abelithseijas602@gmail.com",
                "labor" => "PROMOTORES",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "LEONARDO INFANTE",
                "parroquia" => "VALLE DE LA PASCUA",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "17081893",
                "nombre" => "YNGRID YADEXY",
                "apellido" => "CAMPOS FLORES",
                "telefono" => "0426-7418729",
                "correo" => "yngridcampos10@gmail.com",
                "labor" => "PROMOTORES",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "JOSE TADEO MONAGAS",
                "parroquia" => "ALTAGRACIA DE ORITUCO",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "17434806",
                "nombre" => "DIOMELIS",
                "apellido" => "PEREZ FLORES",
                "telefono" => "0426-1449903",
                "correo" => "diomelisperez@gmail.com",
                "labor" => "PROMOTORES",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "LEONARDO INFANTE",
                "parroquia" => "VALLE DE LA PASCUA",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "17950093",
                "nombre" => "CIPRIANO DE JESUS",
                "apellido" => "MARTINEZ AULAR",
                "telefono" => "0426-2403604",
                "correo" => "ciprianomartinez1988@gmail.com",
                "labor" => "ADMINISTRATIVO",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "PEDRO ZARAZA",
                "parroquia" => "ZARAZA",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "18043100",
                "nombre" => "CESAR ENRIQUE",
                "apellido" => "AVILA MORENO",
                "telefono" => "0412-1642074",
                "correo" => "cesar2022avila@gmail.com",
                "labor" => "PROMOTORES",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "JUAN GERMAN ROSCIO",
                "parroquia" => "SAN JUAN",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "18220683",
                "nombre" => "JUAN EDUARDO",
                "apellido" => "FLORES PAEZ",
                "telefono" => "0412-7767180",
                "correo" => "jf2423488@gmail.com",
                "labor" => "PROMOTORES",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "FRANCISCO DE MIRANDA",
                "parroquia" => "CALABOZO",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "18407715",
                "nombre" => "GILBERTO JESUS",
                "apellido" => "MUGUERZA TORREALBA",
                "telefono" => "0412-1994594",
                "correo" => "gilberto0186@gmail.com",
                "labor" => "PROMOTORES",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "JOSE FELIX RIBAS",
                "parroquia" => "TUCUPIDO",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "18643865",
                "nombre" => "JOSE ALEXANDER",
                "apellido" => "RIVAS GUARAMATA",
                "telefono" => "0412-4617486",
                "correo" => "jrivasguaramata8@gmail.com",
                "labor" => "PROMOTORES",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "PEDRO ZARAZA",
                "parroquia" => "SAN JOSE DE UNARE",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "18803525",
                "nombre" => "ZULIMAR ELENA",
                "apellido" => "RODRIGUEZ CEDEÑO",
                "telefono" => "0412-4402654",
                "correo" => "contraloriasocialguarico.24@gmail.com",
                "labor" => "PROMOTORES",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "JUAN GERMAN ROSCIO",
                "parroquia" => "SAN JUAN",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "18895085",
                "nombre" => "YESICA CAROLINA",
                "apellido" => "MENDOZA",
                "telefono" => "0424-3178555",
                "correo" => "mcarola1990@gmail.com",
                "labor" => "PROMOTORES",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "LAS MERCEDES",
                "parroquia" => "LAS MERCEDES DEL LLANO",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "19254163",
                "nombre" => "YENITZA DAIBELIZ",
                "apellido" => "CRUZ LEON",
                "telefono" => "0424-3795024",
                "correo" => "yenitza1989@gmail.com",
                "labor" => "PROMOTORES",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "JUAN GERMAN ROSCIO",
                "parroquia" => "SAN JUAN",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "19533544",
                "nombre" => "MARIA ANGEL",
                "apellido" => "GARCIA HERRERA",
                "telefono" => "0416-5681144",
                "correo" => "mariangelgarcia33@gmail.com",
                "labor" => "PROMOTORES",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "LAS MERCEDES",
                "parroquia" => "LAS MERCEDES DEL LLANO",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "19962804",
                "nombre" => "JEAN CARLOS",
                "apellido" => "ACASME PAEZ",
                "telefono" => "0412-1998713",
                "correo" => "jeanacasme@gmail.com",
                "labor" => "PROMOTORES",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "JOSE FELIX RIBAS",
                "parroquia" => "TUCUPIDO",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "20181127",
                "nombre" => "MOISES SALOMON",
                "apellido" => "GAITAN BRITO",
                "telefono" => "0412-4663702",
                "correo" => "moisesgaitan.mg@gmail.com",
                "labor" => "PROMOTORES",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "CAMAGUAN",
                "parroquia" => "CAMAGUAN",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "20524617",
                "nombre" => "MARUJA MERCEDES",
                "apellido" => "HERNANDEZ CANAGUACAN",
                "telefono" => "0424-3717035",
                "correo" => "hernandezmaruja033@gmail.com",
                "labor" => "PROMOTORES",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "JULIAN MELLADO",
                "parroquia" => "EL SOMBRERO",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "20954067",
                "nombre" => "GREYLA CAROLINA",
                "apellido" => "MARTINEZ ORTEGA",
                "telefono" => "0424-1708501",
                "correo" => "greylamartinez2020@gmail.com",
                "labor" => "PROMOTORES",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "LEONARDO INFANTE",
                "parroquia" => "VALLE DE LA PASCUA",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "20954233",
                "nombre" => "NELVIS JOSE",
                "apellido" => "SALGADO AREVALO",
                "telefono" => "0424-3721411",
                "correo" => "nelvisjosesalgado@gmail.com",
                "labor" => "PROMOTORES",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "CHAGUARAMAS",
                "parroquia" => "CHAGUARAMAS",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "20957843",
                "nombre" => "CESAR GABRIEL",
                "apellido" => "FIGUEROA",
                "telefono" => "0412-9675813",
                "correo" => "cesarplus2095@gmail.com",
                "labor" => "PROMOTORES",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "JOSE FELIX RIBAS",
                "parroquia" => "TUCUPIDO",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "21362284",
                "nombre" => "YENIFER MAIRU",
                "apellido" => "FRUGULLETTI PERALES",
                "telefono" => "0426-6331187",
                "correo" => "yenifer8127@gmail.com",
                "labor" => "PROMOTORES",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "PEDRO ZARAZA",
                "parroquia" => "ZARAZA",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "22888589",
                "nombre" => "JOSE LEONEL",
                "apellido" => "GUZMAN LAYA",
                "telefono" => "0412-4935928",
                "correo" => "leolaya94@gmail.com",
                "labor" => "PROMOTORES",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "SANTA MARIA DE IPIRE",
                "parroquia" => "SANTA MARIA DE IPIRE",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "24662051",
                "nombre" => "OLYMAR VIRGINIA",
                "apellido" => "LIMA GARCIA",
                "telefono" => "0412-7797488",
                "correo" => "limavirginia622@gmail.com",
                "labor" => "PROMOTORES",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "FRANCISCO DE MIRANDA",
                "parroquia" => "CALABOZO",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "24662940",
                "nombre" => "JESUS ENRIQUE",
                "apellido" => "RODRIGUEZ NUÑEZ",
                "telefono" => "0412-7785534",
                "correo" => "jesusenriquerodrigueznunez@gmail.com",
                "labor" => "PROMOTORES",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "FRANCISCO DE MIRANDA",
                "parroquia" => "CALABOZO",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "25130300",
                "nombre" => "DAISON NICOLAS",
                "apellido" => "RANGEL VELASQUEZ",
                "telefono" => "0414-4638362",
                "correo" => "daisonr53@gmail.com",
                "labor" => "ADMINISTRATIVO",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "JUAN GERMAN ROSCIO",
                "parroquia" => "SAN JUAN",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "25133774",
                "nombre" => "GENESIS NORELQUIS",
                "apellido" => "LEOTA VELASQUEZ",
                "telefono" => "0412-8895794",
                "correo" => "genesisleota242@gmail.com",
                "labor" => "PROMOTORES",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "CHAGUARAMAS",
                "parroquia" => "CHAGUARAMAS",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "26615944",
                "nombre" => "GUILLERMO ELOY",
                "apellido" => "PEREZ CABANERIO",
                "telefono" => "0426-2890702",
                "correo" => "eloyperez127@gmail.com",
                "labor" => "PROMOTORES",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "SAN GERONIMO DE GUAYABAL",
                "parroquia" => "GUAYABAL",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "32750541",
                "nombre" => "KARIANGEL CAROLINA",
                "apellido" => "GARCIA ARAY",
                "telefono" => "0424-2753441",
                "correo" => "kariangelaray99@gmail.com",
                "labor" => "PROMOTORES",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "PEDRO ZARAZA",
                "parroquia" => "ZARAZA",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "9452514",
                "nombre" => "CARMEN CRISTINA",
                "apellido" => "GIL",
                "telefono" => "0412-0977662",
                "correo" => "crisstty00@hotmail.com",
                "labor" => "PROMOTORES",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "JUAN GERMAN ROSCIO",
                "parroquia" => "SAN JUAN",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "26864620",
                "nombre" => "CRISTIAN JOSE",
                "apellido" => "NAVAS GARCIA",
                "telefono" => "0412-1149572",
                "correo" => "cristianavas865@gmail.com",
                "labor" => "PROMOTORES",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "SANTA MARIA DE IPIRE",
                "parroquia" => "SANTA MARIA DE IPIRE",
                "observacion" => null,
                "fecha" => null
            ],
            [
                "cedula" => "17714799",
                "nombre" => "MARELYS CAROLINA",
                "apellido" => "ARAY CORREA",
                "telefono" => "0412-4457580",
                "correo" => "mariel1486@gmail.com",
                "labor" => "COORDINADOR(A) ESTADAL",
                "categoria" => null,
                "ente" => "FUNDACOMUNAL",
                "redi" => "LLANOS",
                "estado" => "GUARICO",
                "municipio" => "JUAN GERMAN ROSCIO",
                "parroquia" => "GUARICO",
                "observacion" => null,
                "fecha" => null
            ]
        ];

        foreach ($trabajadores as $nomina){
            GestionHumana::create([
                'cedula' => $nomina['cedula'],
                'nombre' => $nomina['nombre'],
                'apellido' => $nomina['apellido'],
                'telefono' => $nomina['telefono'],
                'email' => $nomina['correo'],
                'tipos_personal_id' => $this->getTipoPersonal($nomina['labor']),
                'categorias_id' => $this->getCategoria($nomina['categoria']),
                'ente' => $nomina['ente'],
                'redis_id' => $this->getRedi($nomina['redi']),
                'estados_id' => $this->getEstado($nomina['estado']),
                'municipios_id' => $this->getMunicipio($nomina['municipio']),
                'parroquia' => $nomina['parroquia'],
                'observacion' => $nomina['observacion'],
                'fecha' => $nomina['fecha'] ? Carbon::parse($nomina['fecha']) : null
            ]);
        }
    }

    protected function getTipoPersonal($nomina)
    {
        $tipo = TipoPersonal::where('nombre', $nomina)->first();
        return $tipo?->id;
    }

    protected function getCategoria($nomina)
    {
        $categoria = Categoria::where('nombre', $nomina)->first();
        return $categoria?->id;
    }

    protected function getRedi($nomina)
    {
        $redi = Redi::where('nombre', $nomina)->first();
        return $redi?->id;
    }

    protected function getEstado($nomina)
    {
        $estado = Estado::where('nombre', $nomina)->first();
        return $estado?->id;
    }

    protected function getMunicipio($nomina)
    {
        $municipio = Municipio::where('nombre', $nomina)->first();
        return $municipio?->id;
    }

}
